/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlybanhang.Fram;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import quanlybanhang.ConnectToSQLServer;
import static quanlybanhang.ConnectToSQLServer.getConnection;
import quanlybanhang.NhanVien;

/**
 *
 * @author Admin
 */
public class NhanVienForm extends javax.swing.JFrame {
    final String header []={ "Mã NV","Tên NV","Ngày sinh","email","giới tính","sdt","địa chỉ"};
    final DefaultTableModel tb = new DefaultTableModel(header,0);
    ConnectToSQLServer cn = new ConnectToSQLServer();
    Connection conn;
    private boolean flase;
   

    /**
     * Creates new form NhanVienForm
     */
    public NhanVienForm() {
       initComponents();
        setLocationRelativeTo(null);// hiển thị form ra giữa màn hình
        LoatBang();
       
    }
     public void LoatBang(){
        try {
            conn = cn.getConnection();
            String sql = "SELECT *FROM NHANVIEN "
                    + "";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            tb.setRowCount(0);
            while (rs.next()) {
               Object personObject[] = {
                    rs.getString("manv"),
                    rs.getString("tennv"),
                    rs.getString("ngaysinh"),
                    rs.getString("email"),
                    rs.getString("gioitinh"),
                    rs.getString("sdt"),
                      rs.getString("diachi") 
                };
                tb.addRow(personObject);
                jTablenhanvien.setModel(tb);
            }
            
           st.close();
           rs.close();
           conn.close();
        } catch (Exception e) {
        }
   
        jTablenhanvien.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
               if (jTablenhanvien.getSelectedRow()>=0){
                   jTextFieldMaNV.setText(jTablenhanvien.getValueAt(jTablenhanvien.getSelectedRow(), 0)+"");
                   jTextFieldTenNV1.setText(jTablenhanvien.getValueAt(jTablenhanvien.getSelectedRow(), 1)+"");
                   jTextFieldNgaysinh.setText(jTablenhanvien.getValueAt(jTablenhanvien.getSelectedRow(), 2)+"");
                   //jTextFieldmakh.setText(jTable_Khachhang.getValueAt(jTable_Khachhang.getSelectedRow(), 3)+"");
                   jTextFieldEmail.setText(jTablenhanvien.getValueAt(jTablenhanvien.getSelectedRow(), 4)+"");
                   jTextFieldDiachi.setText(jTablenhanvien.getValueAt(jTablenhanvien.getSelectedRow(), 6)+"");
                    jTextFieldSDT.setText(jTablenhanvien.getValueAt(jTablenhanvien.getSelectedRow(), 5)+"");
               }
            }
        });
    }
// Hàm này xẽ xóa trắng sau khi thêm sửa xóa
    private void Xoatrang(){
        jTextFieldMaNV.setText("");
        jTextFieldTenNV1.setText("");
        jTextFieldEmail.setText("");
        jTextFieldNgaysinh.setText("");
        jTextFieldDiachi.setText("");
        jTextFieldSDT.setText("");
        LoatBang();
        jTextFieldMaNV.setEnabled(true);
        //sau khi them thanh cong thi tu load ma moi luon
       // automakh();
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void jTablenhanvienMouseClicked(java.awt.event.MouseEvent evt) {                                            

        // TODO add your handling code here:
        int i = jTablenhanvien.getSelectedRow();
        TableModel model = jTablenhanvien.getModel();
        jTextFieldMaNV.setText(model.getValueAt(i, 0).toString());
        jTextFieldTenNV1.setText(model.getValueAt(i, 1).toString());
        jTextFieldNgaysinh.setText(model.getValueAt(i, 2).toString());
        jTextFieldEmail.setText(model.getValueAt(i, 3).toString());
        //Gioi tính 
        //jTextField.setText(model.getValueAt(i, 4).toString());
        jTextFieldSDT.setText(model.getValueAt(i, 5).toString());
        jTextFieldDiachi.setText(model.getValueAt(i, 6).toString());
    }                                          

           
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbbNgay = new javax.swing.JPanel();
        jLabeltennv = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        jLabelsdt = new javax.swing.JLabel();
        jLabelgioitinh = new javax.swing.JLabel();
        jLabeldiachi = new javax.swing.JLabel();
        jTextFieldSDT = new javax.swing.JTextField();
        jLabelmanv = new javax.swing.JLabel();
        jTextFieldMaNV = new javax.swing.JTextField();
        rbtnNam = new javax.swing.JRadioButton();
        rbtnNu = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jTextFieldDiachi = new javax.swing.JTextField();
        jLabelngaysinh = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldNgaysinh = new javax.swing.JTextField();
        jTextFieldTenNV1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton_ThemNV = new javax.swing.JButton();
        jButton_Reset = new javax.swing.JButton();
        jButton_XoaNV = new javax.swing.JButton();
        jButton_SuaNV = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablenhanvien = new javax.swing.JTable();
        jTextField_tennv = new javax.swing.JTextField();
        jButton_Timkiem = new javax.swing.JButton();
        jButton_Thoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ NHÂN VIÊN");
        setBackground(new java.awt.Color(0, 153, 153));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));

        jLabel8.setBackground(new java.awt.Color(51, 255, 255));
        jLabel8.setFont(new java.awt.Font("Sitka Display", 1, 36)); // NOI18N
        jLabel8.setText("QUẢN LÝ NHÂN VIÊN");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlybanhang/Fram/HinhAnh/cogwheel.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(385, 385, 385)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        cbbNgay.setBackground(new java.awt.Color(204, 204, 204));
        cbbNgay.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N
        cbbNgay.setToolTipText("QUẢN LÝ KHÁCH HÀNG");

        jLabeltennv.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabeltennv.setText("Tên NV :");

        Email.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Email.setText("Email : ");

        jLabelsdt.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelsdt.setText("Số ĐT");

        jLabelgioitinh.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelgioitinh.setText("Giới tính:");

        jLabeldiachi.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabeldiachi.setText("Địa chỉ :");

        jTextFieldSDT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSDTActionPerformed(evt);
            }
        });

        jLabelmanv.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelmanv.setText("Mã NV :");

        jTextFieldMaNV.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        buttonGroup1.add(rbtnNam);
        rbtnNam.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rbtnNam.setSelected(true);
        rbtnNam.setText("Nam");
        rbtnNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNamActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnNu);
        rbtnNu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rbtnNu.setText("Nữ");
        rbtnNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNuActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setText("Thêm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextFieldDiachi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldDiachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDiachiActionPerformed(evt);
            }
        });

        jLabelngaysinh.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelngaysinh.setText("Ngày sinh :");

        jTextFieldEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTextFieldNgaysinh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTextFieldTenNV1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        jButton_ThemNV.setBackground(new java.awt.Color(255, 153, 153));
        jButton_ThemNV.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton_ThemNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlybanhang/Fram/HinhAnh/themkhachhang-25.png"))); // NOI18N
        jButton_ThemNV.setText("Thêm NV");
        jButton_ThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemNVActionPerformed(evt);
            }
        });

        jButton_Reset.setBackground(new java.awt.Color(255, 153, 153));
        jButton_Reset.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton_Reset.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Tài liệu\\NetBeansProjects\\QLBanHang\\src\\qlbanhang\\HinhAnh\\refresh-25.png")); // NOI18N
        jButton_Reset.setText("Reset");
        jButton_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ResetActionPerformed(evt);
            }
        });

        jButton_XoaNV.setBackground(new java.awt.Color(255, 153, 153));
        jButton_XoaNV.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton_XoaNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlybanhang/Fram/HinhAnh/xoa-25.png"))); // NOI18N
        jButton_XoaNV.setText("Xóa NV");
        jButton_XoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaNVActionPerformed(evt);
            }
        });

        jButton_SuaNV.setBackground(new java.awt.Color(255, 153, 153));
        jButton_SuaNV.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton_SuaNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlybanhang/Fram/HinhAnh/sua-25.png"))); // NOI18N
        jButton_SuaNV.setText("Sửa NV");
        jButton_SuaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_XoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_SuaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_ThemNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_ThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton_SuaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jButton_XoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout cbbNgayLayout = new javax.swing.GroupLayout(cbbNgay);
        cbbNgay.setLayout(cbbNgayLayout);
        cbbNgayLayout.setHorizontalGroup(
            cbbNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbbNgayLayout.createSequentialGroup()
                .addGroup(cbbNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cbbNgayLayout.createSequentialGroup()
                        .addGroup(cbbNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cbbNgayLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(cbbNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelngaysinh)
                                    .addGroup(cbbNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelgioitinh)
                                        .addComponent(Email))
                                    .addGroup(cbbNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelmanv)
                                        .addComponent(jLabeltennv))))
                            .addGroup(cbbNgayLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabelsdt))
                            .addGroup(cbbNgayLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabeldiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cbbNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTenNV1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(cbbNgayLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(rbtnNam)
                        .addGap(66, 66, 66)
                        .addComponent(rbtnNu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(cbbNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cbbNgayLayout.createSequentialGroup()
                    .addContainerGap(471, Short.MAX_VALUE)
                    .addComponent(jButton4)
                    .addGap(116, 116, 116)))
        );
        cbbNgayLayout.setVerticalGroup(
            cbbNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbbNgayLayout.createSequentialGroup()
                .addGroup(cbbNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cbbNgayLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(cbbNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelmanv)
                            .addComponent(jTextFieldMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(cbbNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeltennv)
                            .addComponent(jTextFieldTenNV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(cbbNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelngaysinh)
                            .addComponent(jTextFieldNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(cbbNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Email)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(cbbNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelgioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnNu)
                            .addComponent(rbtnNam))
                        .addGap(41, 41, 41)
                        .addGroup(cbbNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelsdt))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cbbNgayLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(cbbNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeldiachi))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(cbbNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cbbNgayLayout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(459, Short.MAX_VALUE)))
        );

        jTablenhanvien.setBackground(new java.awt.Color(204, 204, 204));
        jTablenhanvien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTablenhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Họ và tên", "Năm Sinh", "Email", "Giới tính", "SĐT", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablenhanvien);

        jTextField_tennv.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jButton_Timkiem.setBackground(new java.awt.Color(255, 153, 153));
        jButton_Timkiem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton_Timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlybanhang/Fram/HinhAnh/search-icon-32.png"))); // NOI18N
        jButton_Timkiem.setText("Tìm kiếm");
        jButton_Timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TimkiemActionPerformed(evt);
            }
        });

        jButton_Thoat.setBackground(new java.awt.Color(255, 153, 153));
        jButton_Thoat.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlybanhang/Fram/HinhAnh/logout-icon-32.png"))); // NOI18N
        jButton_Thoat.setText("Thoát");
        jButton_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(cbbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jButton_Timkiem)
                        .addGap(76, 76, 76)
                        .addComponent(jTextField_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(637, 637, 637))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Timkiem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentShown

    private void jTextFieldSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSDTActionPerformed

    private void rbtnNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnNamActionPerformed

    private void rbtnNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnNuActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
   
    private void jButton_ThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemNVActionPerformed
      
       
        conn = cn.getConnection();
        try {
            if(jTextFieldMaNV.getText().equals("") || jTextFieldTenNV1.getText().equals("")||jTextFieldNgaysinh.getText().equals("") 
                    ||jTextFieldEmail.getText().equals("") ||jTextFieldDiachi.getText().equals("")|| jTextFieldSDT.getText().equals("")){
             JOptionPane.showMessageDialog(this,"Bạn Cần cập nhật đủ dữ liệu ");
             }else{
                StringBuffer sb = new StringBuffer();
                String SQL_check_pk="SELECT MaNV FROM NHANVIEN WHERE MaNV = '"+jTextFieldMaNV.getText()+"'";
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery(SQL_check_pk);
                if(rs.next()){
                    sb.append("Mã nhân viên đã bị trùng");
                }
                if(sb.length()>0){ //Nếu if kia đúng nó xẽ thêm vào sb 1 đoạn String , kiểm tra độ dài chuỗi này nếu lớn hơn 0 tức là có thông báo thì 
                    JOptionPane.showConfirmDialog(this,sb.toString());
                    rs.close();
                }else{
                   String sql = "INSERT INTO NHANVIEN VALUES(?,?,?,?,?,?,?)";
                   PreparedStatement pst = conn.prepareStatement(sql);
                   String manv = jTextFieldMaNV.getText();                   
                   String hoten = jTextFieldTenNV1.getText();
                   String ngaysinh = jTextFieldNgaysinh.getText();
                    String sdt = jTextFieldSDT.getText();
                   String sex = "";
                   if(rbtnNam.isSelected()){
                       sex = rbtnNam.getText();
                   }else{
                       sex = rbtnNu.getText();
                   }
                   String email = jTextFieldEmail.getText();
                   String diachi = jTextFieldDiachi.getText();
                   pst.setString(1, manv);                   
                   pst.setString(2, hoten);
                   pst.setString(3, ngaysinh);
                   pst.setString(4, email);
                   pst.setString(5, sex);
                    pst.setString(6, sdt);
                   pst.setString(7, diachi);
                   int kq = pst.executeUpdate();
                   if(kq>0){
                       JOptionPane.showMessageDialog(this, "Thêm mới thành công !");
                       LoatBang();
                       Xoatrang();
                           
                   }
                }
            conn.close();
        }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_jButton_ThemNVActionPerformed

 
    
    private void jButton_SuaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaNVActionPerformed
          
           conn = cn.getConnection();
        try {
           
            if( jTextFieldMaNV.getText().equals("") || jTextFieldTenNV1.getText().equals("")||jTextFieldNgaysinh.getText().equals("") 
                    ||jTextFieldEmail.getText().equals("") ||jTextFieldDiachi.getText().equals("")){
             JOptionPane.showMessageDialog(this,"Bạn Cần cập nhật đủ dữ liệu ");
             }else{
                String sql = "UPDATE NHANVIEN SET TenNV =?, ngaysinh=?, email=?,gioitinh=?, sdt=?,  diachi=? where manv=?";
                         
                                                  //1        2          3      4         5            6 => vi tri
               PreparedStatement pst = conn.prepareStatement(sql);
                
                   String manv = jTextFieldMaNV.getText();                   
                   String hoten = jTextFieldTenNV1.getText();
                   String ngaysinh = jTextFieldNgaysinh.getText();
                    String sdt = jTextFieldSDT.getText();
                   String sex = "";
                   if(rbtnNam.isSelected()){
                       sex = rbtnNam.getText();
                   }else{
                       sex = rbtnNu.getText();
                   }
                   String email = jTextFieldEmail.getText();
                   String diachi = jTextFieldDiachi.getText();
                   pst.setString(7, manv);                   
                   pst.setString(1, hoten);
                   pst.setString(2, ngaysinh);
                   pst.setString(3, email);
                   pst.setString(4, sex);
                    pst.setString(5, sdt);
                   pst.setString(6, diachi);
                   int kq = pst.executeUpdate();
                    if(kq>0){
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công !");
                    Xoatrang();
                 }
             }
             
            conn.close();
        
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_jButton_SuaNVActionPerformed

    private void jButton_XoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaNVActionPerformed
        // TODO add your handling code here:
         conn=cn.getConnection();
        try {
            
            // Tạo một đối tượng để thực hiện công việc
             String query = "DELETE FROM NHANVIEN WHERE MaNV = '" + jTextFieldMaNV.getText() + "'";
            Statement st = conn.createStatement();
            int chk = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn xóa chứ !","Thông báo",JOptionPane.YES_NO_OPTION);
            if(chk==JOptionPane.YES_NO_OPTION){
                st.executeUpdate(query);
                Xoatrang();
                JOptionPane.showMessageDialog(this, "Xóa thành công !");
            }
        } catch (Exception ex) {

            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton_XoaNVActionPerformed

    private void jButton_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ResetActionPerformed
        // TODO add your handling code here:
        jTextFieldMaNV.setText("");
        jTextFieldTenNV1.setText("");
        jTextFieldEmail.setText("");
        jTextFieldDiachi.setText("");
        jTextFieldNgaysinh.setText("");
        jTextFieldSDT.setText("");
         jTextField_tennv.setText("");
        
    }//GEN-LAST:event_jButton_ResetActionPerformed

    private void jButton_TimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TimkiemActionPerformed
          conn = cn.getConnection();
         try {
              if( jTextField_tennv.getText().equals("")){
             JOptionPane.showMessageDialog(this,"Nhập Tên nhân viên cần tìm kiếm ");
             }else{
            String sql = "SELECT *FROM NHANVIEN where TenNV like '%"+jTextField_tennv.getText()+"%' order by manv desc";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            tb.setRowCount(0);
            while (rs.next()) {
               Object personObject[] = {
                  rs.getString("manv"),
                    rs.getString("tennv"),
                    rs.getString("ngaysinh"),
                    rs.getString("email"),
                    rs.getString("gioitinh"),
                    rs.getString("sdt"),
                    rs.getString("diachi")
                };
                tb.addRow(personObject);
                jTablenhanvien.setModel(tb);
                
              }
             rs.close();
           conn.close();
            }
          
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton_TimkiemActionPerformed

    private void jButton_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThoatActionPerformed
        // TODO add your handling code here:
        jButton_Thoat.setToolTipText("Click để thoát chương trình ");
        int selected = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thoát chương"
            + " trình không", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (selected == JOptionPane.YES_NO_OPTION) {
            this.dispose();

        }
    }//GEN-LAST:event_jButton_ThoatActionPerformed

    private void jTextFieldDiachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDiachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDiachiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cbbNgay;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_Reset;
    private javax.swing.JButton jButton_SuaNV;
    private javax.swing.JButton jButton_ThemNV;
    private javax.swing.JButton jButton_Thoat;
    private javax.swing.JButton jButton_Timkiem;
    private javax.swing.JButton jButton_XoaNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabeldiachi;
    private javax.swing.JLabel jLabelgioitinh;
    private javax.swing.JLabel jLabelmanv;
    private javax.swing.JLabel jLabelngaysinh;
    private javax.swing.JLabel jLabelsdt;
    private javax.swing.JLabel jLabeltennv;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablenhanvien;
    private javax.swing.JTextField jTextFieldDiachi;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldMaNV;
    private javax.swing.JTextField jTextFieldNgaysinh;
    private javax.swing.JTextField jTextFieldSDT;
    private javax.swing.JTextField jTextFieldTenNV1;
    private javax.swing.JTextField jTextField_tennv;
    private javax.swing.JRadioButton rbtnNam;
    private javax.swing.JRadioButton rbtnNu;
    // End of variables declaration//GEN-END:variables

    

    
}
